const { queryHelpers } = require("@testing-library/react");

export const BooksGenres = [
    "Action and adventure",
    "Art/architecture",
    "Alternate history",
    "Autobiography",
    "Anthology",
    "Biography",
    "Chick lit",
    "Business/economics",
    "Children's",
    "Crafts/hobbies",
    "Classic",
    "Cookbook",
    "Comic book",
    "Diary",
    "Dictionary",
    "Crime",
    "Encyclopedia",
    "Drama",
    "Guide",
    "Fairytale",
    "Health/fitness",
    "Fantasy",
    "History",
    "Graphic novel",
    "Home and garden",
    "Historical fiction",
    "Humor",
    "Horror",
    "Journal",
    "Mystery",
    "Math",
    "Paranormal romance",
    "Memoir",
    "Picture book",
    "Philosophy",
    "Poetry",
    "Prayer",
    "Political thriller",
    "Religion, spirituality, and new age",
    "Romance",
    "True crime",
    "Science fiction",
    "Review",
    "Short story",
    "Science",
    "Suspense",
    "Self queryHelpers",
    "Thriller",
    "Sports and leisure",
    "Western",
    "Travel"
]
